src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GroupRepository::class)]
#[ORM\Table(name: '`group`')]
class Group
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'groups')]
    private Collection $user;

    #[ORM\Column(length: 255)]
    private ?string $Ecole = null;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }

    public function getEcole(): ?string
    {
        return $this->Ecole;
    }

    public function setEcole(string $Ecole): self
    {
        $this->Ecole = $Ecole;

        return $this;
    }



}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Group;
use App\Entity\User;
use App\Repository\GroupRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileController extends AbstractController
{
    #[Route('app/profile', name: 'app_pages_profile')]
    public function index(ManagerRegistry $managerRegistry): Response
    {
        return $this->render('app/pages/profile/index.html.twig', [
            //'group' => $managerRegistry->getRepository(Group::class)->findBy(['user'=>$managerRegistry->getRepository(User::class)->findOneBy(['id' => $this->getUser()->getId()])]),
            //'group' => $managerRegistry->getRepository(Group::class)->findOneBy(['id' => '1'])
            'groups' => $managerRegistry->getRepository(Group::class)->findAll(),
        ]);
    }
}

templates/app/pages/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('app_pages_profile') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app_pages_profile') }}
{% endblock %}

{% block title %}My Learning{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-2 mt-5">

        </div>
        <div class="col-8 mt-5">
            <h1>Paramètres Utilisateur</h1>
                <div class="mt-5">
                {% if is_granted('ROLE_ADMIN') %}
                <hr>
                <h2 class="text-center">Vous êtes Administrateur</h2>
                    <div class="row">
                        <div class="col-8">
                            <a class="btn btn-success " href="{{ path('admin') }}">Accéder à l'interface d'administration</a>
                        </div>
                    </div>

                {% elseif is_granted('ROLE_PROF') %}

                <h2 class="text-center">Vous êtes Professeur</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn btn-success" href="">Accéder à l'interface des prof</a>
                        </div>
                    </div>

                {% elseif is_granted('ROLE_ELEVE') %}

                <h2 class="text-center">Vous êtes Eleve</h2>
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn btn-success" href="">Accéder à l'interface des élèves</a>
                        </div>
                    </div>

                {% endif %}
                <hr>

                <div>
                    <h2>Détails de votre compte</h2>
                    Prénom : <strong>{{ app.user.firstname }}</strong> <br>
                    Nom : <strong>{{ app.user.lastname }}</strong> <br>
                    Adresse mail : <strong>{{ app.user.email }}</strong> <br>
                    {% if is_granted('ROLE_PROF') or is_granted('ROLE_ELEVE') %}
                        Ecole :
                            {% for group in app.user.getGroups() %}
                                <strong>{{ group.ecole }}</strong><br>
                            {% endfor %}
                        {% if is_granted('ROLE_ELEVE') %}
                            Classe :
                            {% for group in app.user.getGroups() %}
                                <strong>{{ group.name }}</strong>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                </div>

                <div class="row">
                    <div class="col-md-4">
                        <div class="account-item">
                            <a class="btn btn-success" href="{{ path('app_account_password') }}">Modifier mon mot de passe</a>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <div class="col-2">

        </div>
    </div>
{% endblock %}