src/Entity/Lessons.php
<?php

namespace App\Entity;

use App\Repository\LessonsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LessonsRepository::class)]
class Lessons
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Desciption = null;

    #[ORM\Column]
    private ?int $position = null;

    #[ORM\ManyToOne(inversedBy: 'lessons')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Matter $Matter = null;

    #[ORM\OneToMany(mappedBy: 'LessonSection', targetEntity: LessonSection::class)]
    private Collection $lessonSections;

    public function __construct()
    {
        $this->lessonSections = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->Titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDesciption(): ?string
    {
        return $this->Desciption;
    }

    public function setDesciption(string $Desciption): self
    {
        $this->Desciption = $Desciption;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getMatter(): ?Matter
    {
        return $this->Matter;
    }

    public function setMatter(?Matter $Matter): self
    {
        $this->Matter = $Matter;

        return $this;
    }

    /**
     * @return Collection<int, LessonSection>
     */
    public function getLessonSections(): Collection
    {
        return $this->lessonSections;
    }

    public function addLessonSection(LessonSection $lessonSection): self
    {
        if (!$this->lessonSections->contains($lessonSection)) {
            $this->lessonSections->add($lessonSection);
            $lessonSection->setLessonSection($this);
        }

        return $this;
    }

    public function removeLessonSection(LessonSection $lessonSection): self
    {
        if ($this->lessonSections->removeElement($lessonSection)) {
            // set the owning side to null (unless already changed)
            if ($lessonSection->getLessonSection() === $this) {
                $lessonSection->setLessonSection(null);
            }
        }

        return $this;
    }
}

src/Controller/ClassController.php
<?php

namespace App\Controller;

use App\Entity\Lessons;
use App\Entity\Matter;
use App\Form\LessonType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ClassController extends AbstractController
{
    #[Route('/class/{matter}', name: 'app_pages_class')]
    public function index(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $routeParameters = $request->attributes->get('_route_params');

        if (['matter' => 'redirect'] == $routeParameters) {
            $this->addFlash('warning', 'clique sur una matière espèce de bouffon. comment tu veux quje devine après');

            return $this->redirectToRoute('front_matter');
        } else {
            $matterTitle = $request->get('matter');
            $lesson = new Lessons();

            $form = $this->createForm(LessonType::class, $lesson, ['matterTitle' => $matterTitle]);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $titre = $form['titre']->getData();

                $managerRegistry->getManager()->persist($lesson);
                $managerRegistry->getManager()->flush();

                return $this->redirectToRoute('app_lesson_section', ['lessonSection' => $titre]);
            }

            return $this->render('app/pages/class/index.html.twig', [
                'form' => $form->createView(),
                'lessons' => $managerRegistry->getRepository(Lessons::class)->findBy(['Matter' => $managerRegistry->getRepository(Matter::class)->findOneBy(['Title' => $request->get('matter')])]),
            ]);
        }
    }
}

templates/app/pages/class/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('app_pages_class') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app_pages_class') }}
{% endblock %}

{% block body %}
    <h1>Class page</h1>

    <div class="row">
        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_PROF') %}
            <div class="col-8">
        {% else %}
            <div class="col-12">
        {% endif%}

        <h3>Liste des cours</h3>

        {% for lesson in lessons %}
            <div class="card text-bg-light mb-3">
                <div class="card-header">
                    <h4 class="card-title text-primary me-auto">{{ lesson.titre }}</h4>
                </div>
                <div class="card-body">
                    Description : {{ lesson.desciption }}<br>
                    <div class="text-center mt-3"><a class="btn btn-lg btn-warning text-white" href="{{ path('app_lesson_section', {'lessonSection' : lesson.titre}) }}">Accéder au cours</a></div>
                </div>
            </div>
        {% endfor %}

        </div>
        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_PROF') %}
            <div class="col-4">
                <h3>Ajouter un cours</h3>

                {{ form_start(form) }}
                    {{ form_row(form.titre) }}
                    {{ form_row(form.desciption) }}
                    {{ form_row(form.matter) }}
                    {{ form_row(form.position) }}
                <button type="submit" class="btn btn-outline-primary">Enregistrer</button>
            </div>
        </div>
    </div>
        {{ form_end(form) }}
    {% endif %}
{% endblock %}